### ISSUE TITLE
LLVM build failure: no member named 'numeric_limits' in namespace 'std'

### ISSUE THREAD

**Issue by swkim101** [S2E/s2e-env#453]
`s2e build` prints following errors.

```
In file included from /home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.cc:15:
/home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.h:17:30: error: no member named 'numeric_limits' in namespace 'std'
  static const T kmax = std::numeric_limits<T>::max();
                        ~~~~~^
/home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.h:17:45: error: 'T' does not refer to a value
  static const T kmax = std::numeric_limits<T>::max();
                                            ^
/home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.h:8:20: note: declared here
template <typename T>
                   ^
/home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.h:17:47: error: no member named 'max' in the global namespace; did you mean 'kmax'?
  static const T kmax = std::numeric_limits<T>::max();
                                              ^~~~~
                                              kmax
/home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.h:17:18: note: 'kmax' declared here
  static const T kmax = std::numeric_limits<T>::max();
                 ^
/home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.h:17:18: error: default initialization of an object of const type 'const long'
  static const T kmax = std::numeric_limits<T>::max();
                 ^
                      = 0
/home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.cc:270:3: note: in instantiation of function template specialization 'AddRange<long>' requested here
  AddRange(&arglist, start, limit, range_multiplier_);
  ^
In file included from /home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.cc:15:
/home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.h:17:18: error: default initialization of an object of const type 'const int'
  static const T kmax = std::numeric_limits<T>::max();
                 ^
                      = 0
/home/sungwoo/s2e/build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.cc:417:3: note: in instantiation of function template specialization 'AddRange<int>' requested here
  AddRange(&thread_counts_, min_threads, max_threads, 2);
  ^
5 errors generated.
make[3]: *** [utils/benchmark/src/CMakeFiles/benchmark.dir/build.make:90: utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:144694: utils/benchmark/src/CMakeFiles/benchmark.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:156: all] Error 2
make: *** [/home/sungwoo/s2e/source/scripts//..//s2e/Makefile:200: stamps/llvm-release-make] Error 2
```

So I manually inserted `#include <limits>` on the top of `build/llvm-10.0.0.src/utils/benchmark/src/benchmark_register.h`, and errors are gone 👍

**Comment by vitalych** [comment]
Looks like an LLVM issue. Perhaps you could try upgrading 10.0 to the most recent one.

**Comment by swkim101** [comment]
Looks s2e does not use a machine's pre-installed llvm, instead it downloads and uses llvm-10.0.0 from Web.

https://github.com/S2E/s2e/blob/fd740053855e9f6ae1011ba42b699a4129306767/Makefile#L74

So, if it were the LLVM issue, other users would see the same errors...

**Comment by vitalych** [comment]
Yes, it downloads and builds it. It's possible others have errors, it works fine for me though.
Would bumping it to 10.0.1 work? I suppose more recent versions would require much larger changes. I re-opened #201 to upgrade it properly.

**Comment by swkim101** [comment]
Would bumping it to 10.0.1 work? -> No
Then 11.0.0 or 11.0.1? -> No 😢
But 12.0.0? -> Yes 👍

FYI:
* Tested on: x86_64 ubuntu 18.04.
* I tested with 16.04's pre-compiled binary since llvm does not provide pre-compiled `llvm-10.0.1`, `llvm-11.0.0`, and `llvm-11.0.1` for ubuntu 18.04.
* llvm puts `#include <limits>` from 12.0.0: 
https://github.com/llvm/llvm-project/blob/d28af7c654d8db0b68c175db5ce212d74fb5e9bc/llvm/utils/benchmark/src/benchmark_register.h#L4
* Work on 12.0.1 or 13.0.0? -> No idea (but it should work)

**Comment by swkim101** [comment]
Unfortunately, building libvmi-release failed under llvm-12.0.0.
```sh
make -j112 -C libvmi-release 
make[1]: Entering directory '/home/sungwoo/s2e_1/build/libvmi-release'
make[2]: Entering directory '/home/sungwoo/s2e_1/build/libvmi-release'
make[3]: Entering directory '/home/sungwoo/s2e_1/build/libvmi-release'
make[3]: Leaving directory '/home/sungwoo/s2e_1/build/libvmi-release'
make[3]: Entering directory '/home/sungwoo/s2e_1/build/libvmi-release'
[  4%] Building CXX object src/CMakeFiles/vmi.dir/DecreeFile.cpp.o
[  9%] Building CXX object src/CMakeFiles/vmi.dir/ElfDwarf.cpp.o
[ 14%] Building CXX object src/CMakeFiles/vmi.dir/ExecutableFile.cpp.o
[ 19%] Building CXX object src/CMakeFiles/vmi.dir/FileProvider.cpp.o
[ 23%] Building CXX object src/CMakeFiles/vmi.dir/PEFile.cpp.o
[ 28%] Building CXX object src/CMakeFiles/vmi.dir/Vmi.cpp.o
[ 33%] Building CXX object src/CMakeFiles/vmi.dir/WindowsCrashDumpGenerator.cpp.o
[ 38%] Building CXX object src/CMakeFiles/vmi.dir/WinKernDumpFile.cpp.o
In file included from /home/sungwoo/s2e_1/source/s2e/libvmi/src/ExecutableFile.cpp:25:
/home/sungwoo/s2e_1/source/s2e/libvmi/include/vmi/ELFFile.h:173:21: error: no viable conversion from 'llvm::StringRef' to 'std::string' (aka 'basic_string<char>')
        std::string moduleName = llvm::sys::path::filename(std::string(file->getName()));
                    ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:448:7: note: candidate constructor not viable: no known conversion from 'llvm::StringRef' to 'const std::basic_string<char> &' for 1st argument
      basic_string(const basic_string& __str)
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:525:7: note: candidate constructor template not viable: no known conversion from 'llvm::StringRef' to 'const char *' for 1st argument
      basic_string(const _CharT* __s, const _Alloc& __a = _Alloc())
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:552:7: note: candidate constructor not viable: no known conversion from 'llvm::StringRef' to 'std::basic_string<char> &&' for 1st argument
      basic_string(basic_string&& __str) noexcept
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:579:7: note: candidate constructor not viable: no known conversion from 'llvm::StringRef' to 'initializer_list<char>' for 1st argument
      basic_string(initializer_list<_CharT> __l, const _Alloc& __a = _Alloc())
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:440:7: note: explicit constructor is not a candidate
      basic_string(const _Alloc& __a) _GLIBCXX_NOEXCEPT
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:650:2: note: explicit constructor is not a candidate
        basic_string(const _Tp& __t, const _Alloc& __a = _Alloc())
        ^
/home/sungwoo/s2e_1/build/llvm-12.0.0.src/include/llvm/ADT/StringRef.h:275:14: note: explicit conversion function is not a candidate
    explicit operator std::string() const { return str(); }
             ^
/home/sungwoo/s2e_1/build/llvm-12.0.0.src/include/llvm/ADT/StringRef.h:278:5: note: candidate function
    operator std::string_view() const {
    ^
In file included from /home/sungwoo/s2e_1/source/s2e/libvmi/src/ExecutableFile.cpp:26:
/home/sungwoo/s2e_1/source/s2e/libvmi/include/vmi/PEFile.h:73:31: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
    void *readDirectory(llvm::BumpPtrAllocator &alloc, unsigned index);
                        ~~~~~~^
/home/sungwoo/s2e_1/source/s2e/libvmi/include/vmi/PEFile.h:205:31: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
    void *readDirectory(llvm::BumpPtrAllocator &alloc, unsigned index);
                        ~~~~~~^
In file included from /home/sungwoo/s2e_1/source/s2e/libvmi/src/PEFile.cpp:32:
/home/sungwoo/s2e_1/source/s2e/libvmi/include/vmi/PEFile.h:73:31: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
    void *readDirectory(llvm::BumpPtrAllocator &alloc, unsigned index);
                        ~~~~~~^
/home/sungwoo/s2e_1/source/s2e/libvmi/include/vmi/PEFile.h:205:31: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
    void *readDirectory(llvm::BumpPtrAllocator &alloc, unsigned index);
                        ~~~~~~^
/home/sungwoo/s2e_1/source/s2e/libvmi/src/PEFile.cpp:78:25: error: no viable conversion from 'llvm::StringRef' to 'std::string' (aka 'basic_string<char>')
            std::string moduleName = llvm::sys::path::filename(std::string(file->getName()));
                        ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:448:7: note: candidate constructor not viable: no known conversion from 'llvm::StringRef' to 'const std::basic_string<char> &' for 1st argument
      basic_string(const basic_string& __str)
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:525:7: note: candidate constructor template not viable: no known conversion from 'llvm::StringRef' to 'const char *' for 1st argument
      basic_string(const _CharT* __s, const _Alloc& __a = _Alloc())
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:552:7: note: candidate constructor not viable: no known conversion from 'llvm::StringRef' to 'std::basic_string<char> &&' for 1st argument
      basic_string(basic_string&& __str) noexcept
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:579:7: note: candidate constructor not viable: no known conversion from 'llvm::StringRef' to 'initializer_list<char>' for 1st argument
      basic_string(initializer_list<_CharT> __l, const _Alloc& __a = _Alloc())
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:440:7: note: explicit constructor is not a candidate
      basic_string(const _Alloc& __a) _GLIBCXX_NOEXCEPT
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:650:2: note: explicit constructor is not a candidate
        basic_string(const _Tp& __t, const _Alloc& __a = _Alloc())
        ^
/home/sungwoo/s2e_1/build/llvm-12.0.0.src/include/llvm/ADT/StringRef.h:275:14: note: explicit conversion function is not a candidate
    explicit operator std::string() const { return str(); }
             ^
/home/sungwoo/s2e_1/build/llvm-12.0.0.src/include/llvm/ADT/StringRef.h:278:5: note: candidate function
    operator std::string_view() const {
    ^
/home/sungwoo/s2e_1/source/s2e/libvmi/src/PEFile.cpp:93:11: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
    llvm::BumpPtrAllocator alloc;
    ~~~~~~^
/home/sungwoo/s2e_1/source/s2e/libvmi/src/PEFile.cpp:179:11: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
    llvm::BumpPtrAllocator alloc;
    ~~~~~~^
/home/sungwoo/s2e_1/source/s2e/libvmi/src/PEFile.cpp:268:35: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
void *PEFile::readDirectory(llvm::BumpPtrAllocator &alloc, unsigned index) {
                            ~~~~~~^
/home/sungwoo/s2e_1/source/s2e/libvmi/src/PEFile.cpp:331:11: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
    llvm::BumpPtrAllocator alloc;
    ~~~~~~^
3 errors generated.
/home/sungwoo/s2e_1/source/s2e/libvmi/src/PEFile.cpp:452:11: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
    llvm::BumpPtrAllocator alloc;
    ~~~~~~^
make[3]: *** [src/CMakeFiles/vmi.dir/build.make:104: src/CMakeFiles/vmi.dir/ExecutableFile.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/sungwoo/s2e_1/source/s2e/libvmi/src/PEFile.cpp:582:11: error: no type named 'BumpPtrAllocator' in namespace 'llvm'
    llvm::BumpPtrAllocator alloc;
    ~~~~~~^
9 errors generated.
```

**Comment by vitalych** [comment]
I suspect there will be many more build issues in other parts of S2E as well. The way I upgrade S2E is to do it for each version of LLVM to avoid being hit by lots of errors, so in this case, build everything for 11.0, check that the test suite passes, then upgrade to 12, test again, then 13, etc.

Depending if you have time to upgrade LLVM, it may be faster to switch to Ubuntu 20.04 instead.

**Comment by vitalych** [comment]
@swkim101 I upgraded to LLVM 13. Could you please check if it works for you?
https://github.com/S2E/s2e/pull/46

**Comment by swkim101** [comment]
How to 's2e init' with the branch?
I tried `s2e init -mb 'issue/201-llvm-2' /home/sungwoo/s2e` but it doesn't work.

**Comment by vitalych** [comment]
You can't. The option that you mention doesn't work for this. You can do it manually as follows:
```
$ ... initialize a new environment normally ...
$ cd source/s2e
$ git fetch
$ get checkout issue/201-llvm-2
$ cd ../..
$ rm -rf build/*
$ s2e build
```

**Comment by swkim101** [comment]
It works 👍
